name: Django Tests

## Define activity which triggers the CI.
on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

  # schedule:
  #   - cron:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Setup Environments
        run: echo $SECRETS_FILE_CONTENT | base64 -d > ../.env
        env:
          SECRETS_FILE_CONTENT: ${{ secrets.SECRETS_FILE_CONTENT }}

      - name: Link with flake8
        run: pip install flake8
          flake8
      - name: Coverage report
        run: coverage run manage.py test
          && coverage report

      - name: Django Testing
        run: python3 manage.py test
