name: Django Tests

## Define activity which triggers the CI.
on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

  # schedule:
  #   - cron:

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: ${{ POSTGRESQL_USER }}
          POSTGRES_PASSWORD: ${{ POSTGRESQL_PASSWORD }}
          POSTGRES_DB: ${{ POSTGRESQL_DB_NAME }}
        ports:
          - 5432:5432

        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Prerequisites
        run: sudo apt-get install libpq-dev

      - name: Install dependencies
        run: python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Setup Environments
        run: echo $SECRETS_FILE_CONTENT | base64 -d > ../.env
        env:
          SECRETS_FILE_CONTENT: ${{ secrets.SECRETS_FILE_CONTENT }}

      - name: Link with flake8
        run: pip install flake8
          flake8

      - name: Coverage report
        run: coverage run manage.py test
          && coverage report

      - name: Django Testing
        run: python3 manage.py test
